{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-okhttp/2.3.2/ktor-client-okhttp-2.3.2.module",
    "group": "io.ktor",
    "module": "ktor-client-okhttp",
    "version": "2.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-okhttp-jvm-2.3.2.jar",
          "url": "ktor-client-okhttp-jvm-2.3.2.jar",
          "size": 63973,
          "sha512": "bfdbedf3b1cd192e659582cdc72203756c6ae1b956a4de07179d4cac620e933e1480dab907051871622d0c44400f959440e16d1409581e471951ae6b860be65d",
          "sha256": "fd6011d5f086b0a3f64ac1c9f8f86f8f544e4ae6e82ff81a736c48c552f43777",
          "sha1": "5ffb6be71200b631b23479fd197131136f70bc2d",
          "md5": "8a76062d162692ebea82e01f80b743b7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-okhttp-jvm-2.3.2.jar",
          "url": "ktor-client-okhttp-jvm-2.3.2.jar",
          "size": 63973,
          "sha512": "bfdbedf3b1cd192e659582cdc72203756c6ae1b956a4de07179d4cac620e933e1480dab907051871622d0c44400f959440e16d1409581e471951ae6b860be65d",
          "sha256": "fd6011d5f086b0a3f64ac1c9f8f86f8f544e4ae6e82ff81a736c48c552f43777",
          "sha1": "5ffb6be71200b631b23479fd197131136f70bc2d",
          "md5": "8a76062d162692ebea82e01f80b743b7"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-client-okhttp-jvm-2.3.2-sources.jar",
          "url": "ktor-client-okhttp-jvm-2.3.2-sources.jar",
          "size": 9102,
          "sha512": "f009ffcc9e10b34f1974468251494c96e2e61c59e9d1443b42467121070f4324f5137bc5cb3df8257c1f9c2deff0bf98ff704d99b3402ca2f79939b48b3f7162",
          "sha256": "01a48862aab80f95fcda4e63837122ab4a27ce6b223e6c585148af9ed7480a41",
          "sha1": "adacd59cb6d84212cb6e74e318a4cbe51c77bf09",
          "md5": "855b2cd047b7742ec3690e3aee9fed4a"
        }
      ]
    }
  ]
}
