{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization/2.3.2/ktor-serialization-2.3.2.module",
    "group": "io.ktor",
    "module": "ktor-serialization",
    "version": "2.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-jvm-2.3.2.jar",
          "url": "ktor-serialization-jvm-2.3.2.jar",
          "size": 24737,
          "sha512": "a136b0961f7bf81eab86ed32aec23832e9e150ab446d5a4efbd2a283cdf00233bfef7d545359ac8e617175952d5f38ca022945bcd051874fdeb522a3c53b7559",
          "sha256": "99b63f5f476ed27d022a80c2af00327a4e24bf6eaf9fe1a4fa7c7f0c66fd15f0",
          "sha1": "23ca3bc995da97cd29de4e9e047da0009ebeedd9",
          "md5": "3eff5a66507e1bdf759c4e77c0cf96fe"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-jvm-2.3.2.jar",
          "url": "ktor-serialization-jvm-2.3.2.jar",
          "size": 24737,
          "sha512": "a136b0961f7bf81eab86ed32aec23832e9e150ab446d5a4efbd2a283cdf00233bfef7d545359ac8e617175952d5f38ca022945bcd051874fdeb522a3c53b7559",
          "sha256": "99b63f5f476ed27d022a80c2af00327a4e24bf6eaf9fe1a4fa7c7f0c66fd15f0",
          "sha1": "23ca3bc995da97cd29de4e9e047da0009ebeedd9",
          "md5": "3eff5a66507e1bdf759c4e77c0cf96fe"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-serialization-jvm-2.3.2-sources.jar",
          "url": "ktor-serialization-jvm-2.3.2-sources.jar",
          "size": 3629,
          "sha512": "a1551eb7084f8cbd619f225eb0cc22a5c8b0ebc7ae2dec0deb3d236059ab869b88762fa3b743be755898c3b20d3a084537e0e37a9d54ae219f4d889049e48c6f",
          "sha256": "ecab047077ce96d38bce84a1377d50efb754e9f66b96962cfc1455ae713fc1c6",
          "sha1": "bb00b8ed4118e06a75537d140269cd1e63083b0c",
          "md5": "a9b00a02ffac3a04713f2b1e81ec2d8f"
        }
      ]
    }
  ]
}
