{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-io",
    "version": "2.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-io-metadata-2.3.2-all.jar",
          "url": "ktor-io-2.3.2-all.jar",
          "size": 50733,
          "sha512": "d2550930900643bb6c7bb5ca52694574daae0248c915936c32239e92cb50f092a36ad2d27caf1a841c750af80a72ef3b0faa7598ffdc37f2f5b9dfab725006de",
          "sha256": "dc74aaa98e651e4496ed4ea8fcfd5120adddbef82deccba9c19f60d76a90c07b",
          "sha1": "9862b9b848d06fd33c657f42b214f684193c5829",
          "md5": "66d78f2057694d5c5c509b59118a2b39"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-io-2.3.2.jar",
          "url": "ktor-io-2.3.2.jar",
          "size": 59187,
          "sha512": "cdb3f712c94c5c0ef73707653660ee138a7fd97acd28c8732abf9c927634d1773e55bfb74605025b4aacbcdff1e00a9dc1fbf50ab1f92bd4805f36c6803c56d5",
          "sha256": "f1f4360154dd91a6a804cad0d136a7f70f958d2d53d41e4db39a22b5670261e7",
          "sha1": "e9b1e27cdf756f70f402b98d57d3d0ce72ed1b1d",
          "md5": "182de080a4b208b7c08bb75c391ac045"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-io-kotlin-2.3.2-sources.jar",
          "url": "ktor-io-2.3.2-sources.jar",
          "size": 103997,
          "sha512": "947c3819039f4452e657a51a139c750dc24a6b840d9e51ae2e7e6a1edd03e3d46214de3fc9ee8937a4644a8f4a902ee0edc10998c8054d603320ea9e5412f57a",
          "sha256": "f3be1f40d06f8c57ef3421c1151705be807835ed6eced9a34003045d0ca84240",
          "sha1": "9b6796a4ef192d9f5839bc9b688b51485e85bda3",
          "md5": "02b745e22f1d98dd1293033654c40d94"
        }
      ]
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-iosarm32/2.3.2/ktor-io-iosarm32-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-iosarm32",
        "version": "2.3.2"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-iosarm32/2.3.2/ktor-io-iosarm32-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-iosarm32",
        "version": "2.3.2"
      }
    },
    {
      "name": "iosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-iosarm32/2.3.2/ktor-io-iosarm32-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-iosarm32",
        "version": "2.3.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-iosarm64/2.3.2/ktor-io-iosarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-iosarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-iosarm64/2.3.2/ktor-io-iosarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-iosarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-iosarm64/2.3.2/ktor-io-iosarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-iosarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-iossimulatorarm64/2.3.2/ktor-io-iossimulatorarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-iossimulatorarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-iossimulatorarm64/2.3.2/ktor-io-iossimulatorarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-iossimulatorarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-iossimulatorarm64/2.3.2/ktor-io-iossimulatorarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-iossimulatorarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-iosx64/2.3.2/ktor-io-iosx64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-iosx64",
        "version": "2.3.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-iosx64/2.3.2/ktor-io-iosx64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-iosx64",
        "version": "2.3.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-iosx64/2.3.2/ktor-io-iosx64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-iosx64",
        "version": "2.3.2"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-io-js/2.3.2/ktor-io-js-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-js",
        "version": "2.3.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-io-js/2.3.2/ktor-io-js-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-js",
        "version": "2.3.2"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-io-js/2.3.2/ktor-io-js-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-js",
        "version": "2.3.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-io-jvm/2.3.2/ktor-io-jvm-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-jvm",
        "version": "2.3.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-io-jvm/2.3.2/ktor-io-jvm-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-jvm",
        "version": "2.3.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-io-jvm/2.3.2/ktor-io-jvm-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-jvm",
        "version": "2.3.2"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-linuxx64/2.3.2/ktor-io-linuxx64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-linuxx64",
        "version": "2.3.2"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-linuxx64/2.3.2/ktor-io-linuxx64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-linuxx64",
        "version": "2.3.2"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-macosarm64/2.3.2/ktor-io-macosarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-macosarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-macosarm64/2.3.2/ktor-io-macosarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-macosarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-macosarm64/2.3.2/ktor-io-macosarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-macosarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-macosx64/2.3.2/ktor-io-macosx64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-macosx64",
        "version": "2.3.2"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-macosx64/2.3.2/ktor-io-macosx64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-macosx64",
        "version": "2.3.2"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-macosx64/2.3.2/ktor-io-macosx64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-macosx64",
        "version": "2.3.2"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-mingwx64/2.3.2/ktor-io-mingwx64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-mingwx64",
        "version": "2.3.2"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-mingwx64/2.3.2/ktor-io-mingwx64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-mingwx64",
        "version": "2.3.2"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-tvosarm64/2.3.2/ktor-io-tvosarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-tvosarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-tvosarm64/2.3.2/ktor-io-tvosarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-tvosarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-tvosarm64/2.3.2/ktor-io-tvosarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-tvosarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-tvossimulatorarm64/2.3.2/ktor-io-tvossimulatorarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-tvossimulatorarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-tvossimulatorarm64/2.3.2/ktor-io-tvossimulatorarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-tvossimulatorarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-tvossimulatorarm64/2.3.2/ktor-io-tvossimulatorarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-tvossimulatorarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-tvosx64/2.3.2/ktor-io-tvosx64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-tvosx64",
        "version": "2.3.2"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-tvosx64/2.3.2/ktor-io-tvosx64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-tvosx64",
        "version": "2.3.2"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-tvosx64/2.3.2/ktor-io-tvosx64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-tvosx64",
        "version": "2.3.2"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-watchosarm32/2.3.2/ktor-io-watchosarm32-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-watchosarm32",
        "version": "2.3.2"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-watchosarm32/2.3.2/ktor-io-watchosarm32-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-watchosarm32",
        "version": "2.3.2"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-watchosarm32/2.3.2/ktor-io-watchosarm32-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-watchosarm32",
        "version": "2.3.2"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-watchosarm64/2.3.2/ktor-io-watchosarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-watchosarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-watchosarm64/2.3.2/ktor-io-watchosarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-watchosarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-watchosarm64/2.3.2/ktor-io-watchosarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-watchosarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-watchossimulatorarm64/2.3.2/ktor-io-watchossimulatorarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-watchossimulatorarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-watchossimulatorarm64/2.3.2/ktor-io-watchossimulatorarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-watchossimulatorarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-watchossimulatorarm64/2.3.2/ktor-io-watchossimulatorarm64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-watchossimulatorarm64",
        "version": "2.3.2"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-watchosx64/2.3.2/ktor-io-watchosx64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-watchosx64",
        "version": "2.3.2"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-watchosx64/2.3.2/ktor-io-watchosx64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-watchosx64",
        "version": "2.3.2"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-watchosx64/2.3.2/ktor-io-watchosx64-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-watchosx64",
        "version": "2.3.2"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-watchosx86/2.3.2/ktor-io-watchosx86-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-watchosx86",
        "version": "2.3.2"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-watchosx86/2.3.2/ktor-io-watchosx86-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-watchosx86",
        "version": "2.3.2"
      }
    },
    {
      "name": "watchosX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-io-watchosx86/2.3.2/ktor-io-watchosx86-2.3.2.module",
        "group": "io.ktor",
        "module": "ktor-io-watchosx86",
        "version": "2.3.2"
      }
    }
  ]
}
